image: node:14

cache:
    paths:
        - node_modules/

before_script:
    - yarn install
test:
    stage: test
    script:
        - yarn test
pages:
    script:
        - yarn build
    artifacts:
        paths:
            - build
    only:
        - master
