image: node:10

cache:
    paths:
        - node_modules/

before_script:
    - yarn install
test:
    stage: test
    script:
        - CI=true npm test
pages:
    stage: deploy
    script:
        - CI=true yarn build
    artifacts:
        paths:
            - build
    only:
        - master
